let a = 10;
let b = 5;
document.writeln("Arithmetic Operators");
document.writeln("<br>");
document.writeln(a+b);
document.writeln("<br>");
document.writeln(a-b);
document.writeln("<br>");
document.writeln(a*b);
document.writeln("<br>");
document.writeln(a/b);
document.writeln("<br>");
document.writeln(a%b);
document.writeln("<br>");
let x = 10;
document.writeln(x++);
document.writeln("<br>");
document.writeln(++x);
document.writeln("<br>");
let y = 8;
document.writeln(--y);
document.writeln("<br>");
document.writeln(y--);
document.writeln("<br>");
document.writeln("Assignment Operators");
document.writeln("<br>");
let c = 10;
c += 5;
document.writeln(c);    
document.writeln("<br>");
c -= 3;
document.writeln(c);
document.writeln("<br>");
c *= 2;
document.writeln(c);            
document.writeln("<br>");
c /= 4;
document.writeln(c);
document.writeln("<br>");
c %= 3;
document.writeln(c);
document.writeln("<br>");

document.writeln("Relational Operators");
document.writeln("<br>");
document.writeln(a > b);
document.writeln("<br>");
document.writeln(a < b);
document.writeln("<br>");
document.writeln(a >= b);
document.writeln("<br>");
document.writeln(a <= b);
document.writeln("<br>");
document.writeln(a == b);
document.writeln("<br>");
document.writeln(a != b);
document.writeln("<br>");
document.writeln(a !== b);
document.writeln("<br>");
document.writeln("Bitwise Operators");
document.writeln("<br>");
document.writeln(a & b);    
document.writeln("<br>");
document.writeln(a | b);
document.writeln("<br>");
document.writeln(a ^ b);
document.writeln("<br>");
document.writeln(~a);
document.writeln("<br>");
document.writeln(a << 2);
document.writeln("<br>");
document.writeln(a >> 2);
document.writeln("<br>");
document.writeln(a >>> 2);
document.writeln("<br>");
document.writeln("Logical Operators");
document.writeln("<br>");
let age = 8;
document.writeln(age > 18 && age < 60);
document.writeln("<br>");
document.writeln(age < 18 || age > 60);
document.writeln("<br>");
document.writeln(!(age > 18 && age < 60));
document.writeln("<br>");
document.writeln("Ternary Operator");
document.writeln("<br>");
let result = (age > 18) ? "Adult" : "Not an adult";
document.writeln(result);
document.writeln("<br>");
document.writeln("Type Operators");
document.writeln("<br>");
document.writeln(typeof a);
document.writeln("<br>");
document.writeln(typeof "Hello");
document.writeln("<br>");
document.writeln(typeof true);
document.writeln("<br>");
document.writeln(typeof undefined);
document.writeln("<br>");
document.writeln(typeof null);
document.writeln("<br>");
document.writeln("Comma Operator");
document.writeln("<br>");
let m = (1, 2, 3);
document.writeln(m);
console.log([1,2,3] instanceof Array);
console.log([1,2,3] instanceof Object);